### ISSUE TITLE
RTCのアクティベート後にどういう動作をするのか分からない

### ISSUE THREAD

**Issue by Nobu19800** [IidaYuki0/Voicing_RTC_for_teleoperation#3]
マニュアルの23ページで「`各コンポーネントをアクティベートする。全てのコンポーネントが緑色になれば，アクティベート完了である`」と書いてありますが、この後どうなるのかがよく分かりません。簡単な動作確認の手順を書いたほうがいいと思います。

**Comment by IidaYuki0** [comment]
宮本様

飯田です。

ご指摘ありがとうございます。マニュアルを修正いたしますので、今しばらくお待ちください。

よろしくお願いします。

飯田

**Comment by IidaYuki0** [comment]
宮本様

飯田です。

マニュアルの該当箇所にアクティベート時の実行ファイルの写真を追加し、動作確認の節を追加いたしました。ご確認のほどよろしくお願いします。

他に不明な箇所がございましたら、ご指導のほどよろしくお願いします。

以上になります。よろしくお願いします。

飯田

**Comment by Nobu19800** [comment]
確認しました。対応していただいてありがとうございました。
